t = 'TAGTATGTTCAGCACGTAGATGTTCACATCCATGTTCAGATGTTCAATGTTCAGGCATGTTCATATGTTCAATGTTCATAGGGAGATCGTTAGAAATATGTTCACTCATAGCGATGTTCACATGTTCAAATGTTCAGTATGTTCAATGTTCAGCCTGATAATGTTCAAATTTATCTATGATGTTCAGCATGTTCATTGCATGTTCACGATGTTCATCCATGTTCAAAATGTTCAAAATGTTCAAATGTTCACCGAATTTCTGATGTTCATTCTATGTTCAATGTTCACCCATGTTCAAATGTTCACATGTTCATAATACATGTTCAATGTTCAATGTTCACAGATGTTCACGATGTTCACATGTTCAGTATATGTTCAGCATGTTCAGCGAGCATGTTCAATGTTCACTAAATGTTCACATGTTCAACCCTATGTTCATATTATGTTCAATGTTCAGATGTTCAGCGATGTTCACCATGTTCAATGAAACGAGATGTTCAGATGTTCAATGTTCACATGTTCAGATGTTCACAATGTTCATGGTTAATGTTCAAGATGTTCAATGTTCAATGTTCAGGAAGAGCAATGTTCAATGTTCAAACTATGTTCACAGCTGAATGTTCAGAACATGTTCACATGTTCAAGGGGCGATGTTCAAGATGTTCAGCATGTTCAATGTTCAATGTTCAAATGTTCAGTAACTATGTTCAAAAAGGAAGTATGTTCAATGTTCACGATGTTCAATGTTCAGCGATGTTCAGAATGTTCAGGATGGTGATGTTCAATGTTCACATGTTCATAACATGTTCAACTTACAATGTTCATGATTCATCAATGTTCATGAATGTTCACCCGGTGCTCGCTCATTCAATATGTTCATCGATGTTCA'
m = 'ATGTTCAAT'
s = []
f_p = 0
l_p = f_p + len(m)
#finding pos using 2 pointer app
while l_p != (len(t) - 1):
    if t[f_p:l_p] == m:
        s.append(f_p)
        l_p = l_p +1 
        f_p = f_p +1 
    else:
        l_p = l_p +1 
        f_p = f_p +1 
#loop through s to print pos
for i in s:
    print(i+1, end =" ")
